name: Build executables for all targets

on:
  workflow_call:
    inputs:
      rust_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      rust_version:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        build: [
          { host: ubuntu-20.04, tool: cargo, target: x86_64-unknown-linux-gnu,    output: hub-recovery },
          { host: ubuntu-20.04, tool: cross, target: aarch64-unknown-linux-gnu,   output: hub-recovery },
          { host: windows-2019, tool: cargo, target: x86_64-pc-windows-msvc,      output: hub-recovery.exe },
          { host: macos-13,     tool: cargo, target: x86_64-apple-darwin,         output: hub-recovery },
          { host: macos-13,     tool: cargo, target: aarch64-apple-darwin,        output: hub-recovery },
        ]
    runs-on: ${{ matrix.build.host }}
    steps:
      - name: Set up Rust
        run: |
          rustup toolchain install ${{ inputs.rust_version }}
          rustup default ${{ inputs.rust_version }}

      - name: Add target
        if: ${{ matrix.build.tool == 'cargo' }}
        run: rustup target add ${{ matrix.build.target }}

      - name: Install cross
        if: ${{ matrix.build.tool == 'cross' }}
        run: cargo install cross --git https://github.com/cross-rs/cross --rev c87a52a

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ${{ matrix.build.tool }} build --release --target ${{ matrix.build.target }}

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: hub-recovery-${{ matrix.build.target }}
          path: target/${{ matrix.build.target }}/release/${{ matrix.build.output }}

  make-macos-universal:
    runs-on: macos-13
    needs: build
    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: hub-recovery-x86_64-apple-darwin
          path: x86_64-apple-darwin

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: hub-recovery-aarch64-apple-darwin
          path: aarch64-apple-darwin

      - name: Make universal executable
        run: |
          lipo -create -output "hub-recovery" "x86_64-apple-darwin/hub-recovery" "aarch64-apple-darwin/hub-recovery"

      - name: Archive universal executable
        uses: actions/upload-artifact@v4
        with:
          name: hub-recovery-universal-apple-darwin
          path: hub-recovery
